config/routes.rb
SleepUnderflow::Application.routes.draw do

  resources :questions, :except => [:edit, :destroy] do
    resources :votes, only: [:create, :update]
    resources :answers, :comments, :only => [:create, :new]
  end
  resources :answers, only: [] do   
    resources :votes, only: [:create, :update]
    resources :comments, :only => [:create, :new]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  match '/signin', to: 'sessions#create', via: 'post'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  root to: "questions#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :user_id, :question_id, :is_best_answer, :score

  has_many :comments, as: :commentable
  has_many :votes, as: :votable
  belongs_to :user
  belongs_to :question

  validates :content, :user_id, :question_id, presence: true

  # REVIEW: look at question tally implementation
  def tally
  	votes.where(up_down: true).count - votes.where(up_down: false).count
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :user_id, :commentable_id, :commentable_type, :content

  validates :user_id, :commentable_id, :commentable_type, :content, presence: true

  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :content, :user_id, :score
  validates :title, :content, :user_id, presence: true

  belongs_to :user
  belongs_to :best_answer, class_name: :Answer
  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  # REVIEW: not tested.
  def tally
    votes.map(&:upvote?).count - votes.map(&:downvote?).count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # REVIEW: please go look at has_secure_password code, it's simple
  has_secure_password
  validates :username, :email, :password, presence: true
  attr_accessible :username, :email, :password, :password_confirmation

  has_many :votes
  has_many :comments
  has_many :questions
  has_many :answers

  def voted? votable
    self.votes.select {|v| v.votable == votable}
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :votable_id, :user_id, :votable_type, :up_down

  belongs_to :user
  belongs_to :votable, polymorphic: true

  validates_uniqueness_of :user_id, scope: [:votable_id, :votable_type]
  validates :votable_id, :votable_type, :user_id, presence: true
  validates_inclusion_of :up_down, :in => [true, false]

  after_save :update_question_answer_score
  after_destroy :update_question_answer_score

  # use :cache_counter (look it up)
  def update_question_answer_score
    votable_obj = self.votable
    votable_obj.score = votable_obj.tally
    votable_obj.save
  end

  def upvote?
    self.up_down
  end


  def downvote?
    !self.up_down
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @answer = Answer.new
  end

  # REVIEW: look at questions#create implementation
  def create
    answer = Answer.new(params[:answer])
    question = Question.find(params[:question_id])
    question.answers << answer
    user = User.find(session[:user_id])
    user.answers << answer
    answer.save
    redirect_to question_path(question)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include Authentication

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable, :only => [:create]
  def new
    @comment = Comment.new
  end


  def create
    @comment = @commentable.comments.build params[:comment]
    if @comment.save
      # do something
    else
      # do something else
    end

  end

  private
  def load_commentable
    @commentable = params[:answer_id] ? Answer.find params[:answer_id] : Question.find params[:id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order("score DESC")
    @vote = Vote.new
  end

  def new
    @question = Question.new
  end

  def create
    user = User.find(session[:user_id]) # user current_user!!!
    @question = current_user.questions.build params[:question]
    if @question.save
      redirect_to question_path(question)
    else
      render :new
    end
  end

  # REVIEW: this action is HUGE and handling too much
  def show
    # create a before_filter that checks if authenticated?
    if session[:user_id] # if current_user
      @vote = Vote.new
      @current_user = User.find(session[:user_id]) #why? you already have current_user
    end
    @question = Question.find(params[:id])
    # this shouldn't be handled in the controller
    best_answer = @question.best_answer
    if best_answer
      @answers = (@question.answers.order("score DESC") - [best_answer]).unshift(best_answer)
    else
      @answers = @question.answers.order("score DESC")
    end
  end

  def update
    question = Question.find(params[:id])
    # this should happen in the model in a before_save
    if params[:question][:best_answer_id] == "0"
      question.best_answer = nil
      question.save
    else
      question.best_answer = Answer.find(params[:question][:best_answer_id])
      question.save
    end
    redirect_to question
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # REVIEW: commented code is evil
    # if user = User.find_by_username(params[:username])
    #   session[:user_id] = user.id
    # else
    #   flash[:notices] = "incorrect login"
    # end
    #   redirect_to root_path
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate params[:password]
      login user
      redirect_to root_path
    else
      # flash[:notices] = "incorrect login"
      # change this to error message
    end
  end

   def destroy
    session.delete :user_id # or session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(params[:user])
    # REVIEW: this should be handled in your model.
    if user.password == user.password_confirmation
      user.save
      login user
      redirect_to question
    else
      flash[:notices] = "signup failed"
      # fix this to eror message
    end
  end


  def show
    # why are you setting an instance variable? why not use current_user.username in the view?
    @username = current_user.username
    @user_answers = current_user.answers
    @user_questions = current_user.questions
    @user_comments = current_user.comments
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def create
    vote = current_user.votes.build(params[:vote])
		vote.save
    if vote.votable_type == "Answer"
      redirect_to question_path(vote.votable.question)
    elsif vote.votable_type == "Question"
      redirect_to question_path(vote.votable)
    end
      
		# to add AJAX ...if you want to
		# 1. Instead of redirect_to, use render json: { score: vote.votable.score }
		# 2. Add 'remote: true' to the options after controller, action, and before form in the button_to
		# 3. Add some Javascript code that listens for an 'ajax:success' event to update the DOM with the new score
	end

  def update
    vote = Vote.find(params[:id])
    if vote.up_down.to_s == params[:vote][:up_down]
      vote.destroy
    else
      vote.up_down = params[:vote][:up_down]
      vote.save
    end
    if vote.votable_type == "Answer"
      redirect_to question_path(vote.votable.question)
    elsif vote.votable_type == "Question"
      redirect_to question_path(vote.votable)
    end 
  end
end


 

  # <%= button_to '^', { url: answer_votes_path(answer, @vote), form: { up_down: 1, votable_type: 'Answer', votable_id: answer.id } }, { class: "vote-button" } %>

app/helpers/application_helper.rb
module ApplicationHelper
  def index_page?
    "/" == request.fullpath || "/questions" == request.fullpath
  end

  def current_vote(votable)
    Vote.where(votable_id: votable.id, votable_type: votable.class.to_s, user_id: current_user.id).first  
  end

  def question_creator?(question)
    user = current_user
    if user
      user.id == question.user_id
    end
  end

  def best_answer?(question, answer_id)
    question.best_answer_id == answer_id
  end
end

app/helpers/session_helper.rb
 module SessionHelper
end

app/views/answers/new.html.erb
<div class='container'><br><center>
<%= form_for @answer, url: {action: "create"} do |f| -%>
  <%= f.text_area :content, size: "40x7", placeholder: "Here is my answer..." %><br />
  <%= f.hidden_field(:user_id, value: current_user.id) %><br><br>
  <%= f.submit "submit answer", class: "btn btn-success" %>
<% end -%>
</center>
</div>

app/views/comments/new.html.erb
<div class='container'><br><center>
<%= form_for @comment do |f| -%>
  <%= f.text_area :content, size: "40x7", placeholder: "This is my comment..." %><br />
 <!-- TODO: This is hardcoded, replace with @user.id -->
  // you have current_user on the controller, use it and don't pass user_id in the form
  <%= f.hidden_field(:user_id, value: 1) %><br><br>
  <%= f.submit "submit comment", class: "btn btn-success" %>
<% end -%>
</center>
</div>

app/views/layouts/_conditional_login_nav_bar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <% if current_user %>
  <div class="navbar-header">
    <li><%= image_tag Gravatar.new(current_user.email).image_url, class: "img-circle" %></li>
    <li><h1>Hi <%= current_user.username %>! </h1></li>
  </div>
  <% end %>

  There is too much going here.
  <div class="collapse navbar-collapse navbar-ex1-collapse">

    <% if flash[:notices] %>
      <%= flash[:notices] %>
    <% end %>
    <ul class="nav navbar-nav navbar-right" style="padding-right: 20px">
      <% if current_user %>

      <%= link_to 'My Profile Page', user_path(current_user), class: 'btn btn-default navbar-btn' %>
      <%= link_to 'Create Question', new_question_path, class: 'btn btn-default navbar-btn' %>
      <%= link_to 'Logout', signout_path, method: 'delete', class: 'btn btn-default navbar-btn' %>

      <% unless index_page? %>
      <%= link_to "Questions", root_path, class: 'btn btn-default navbar-btn' %>
      <% end %>

      <% else %>

      <%= form_tag ("/signin")  do %>
      <%=  text_field_tag("username", nil, placeholder: "username") %>
      <%=  password_field_tag("password", nil, placeholder: "password") %>
      <%= submit_tag("signin", class: 'btn btn-default navbar-btn') %>
      <%= link_to "sign up", new_user_path, class: 'btn btn-info navbar-btn' %>
      <% end %>


      <% end %></div>
    </div></nav><br><br>
  </ul>

  <br><br><br>

  <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SleepUnderflow</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  </head>
  <body>
    <%= render "layouts/conditional_login_nav_bar" %>
    <%= yield %>
  </body>
</html>

app/views/questions/_add_answer_button.html.erb
<div class='container'><br><center>

<% if current_user %>
  <%= form_tag new_question_answer_path(question), method: "get" do %>
    <%= button_tag("add answer", class: 'btn btn-success') %>
  <% end %>

<% end %>

</center>

</div>

app/views/questions/_best_answer_button.html.erb
<div class='container'><br><center>

<% if question_creator?(question) %>
  <% if best_answer?(question, answer_id) %>
    <%= form_for question, url: question_path(question) do |f| %>
      <%= f.hidden_field(:best_answer_id, value: 0) %>
      <%= f.submit "Best Answer" %>
    <% end %>
  <% else %>
    <%= form_for question, url: question_path(question) do |f| %>
      <%= f.hidden_field(:best_answer_id, value: answer_id) %>
      <%= f.submit "Best Answer" %>
    <% end %>
  <% end %>
<% end %>
</center>

<div>

app/views/questions/_comment_button.html.erb
<div class='container'><br><center>

<% if current_user %>
  <%= form_tag(send("new_#{commentable.class.to_s.downcase}_comment_path", commentable), method: "get") do%>
    <%= button_tag("comment on this #{commentable.class.to_s.downcase}", class: 'btn btn-info') %>
  <% end %><br><br>
  <% if commentable.class == Question %> 
    <br><br>
  <% end %>
<% end %>
</center>

</div>

app/views/questions/_vote_form.html.erb
<div class='container'><br><center>

# we can use helper method for this.
<% if current_user %>
  <%if current_user.voted? votable %>
    <%= form_for vote, url: send("#{votable.class.to_s.downcase}_vote_path", votable, vote), html: { class: "edit #{votable.class.to_s.downcase} #{up_down}" } do |f| %>
      <%= f.hidden_field(:up_down, value: vote_boolean) %>
      <%= f.submit "#{up_down}",  class: "#{votable.class.to_s.downcase} #{up_down} btn btn-default" %>
    <% end %>
  <% else %>
    <%= form_for new_vote, url: send("#{votable.class.to_s.downcase}_votes_path", votable, new_vote), html: { class: "new #{votable.class.to_s.downcase} #{up_down}" } do |f| %>
      <%= f.hidden_field(:votable_id, value: votable.id) %>
      <%= f.hidden_field(:votable_type, value: votable.class ) %>
      <%= f.hidden_field(:up_down, value: vote_boolean) %>
      <%= f.submit "#{up_down}", class: "#{votable.class.to_s.downcase} #{up_down} btn btn-default" %>
    <% end %>
  <% end %>
<% end %>

</center>

</div>

app/views/questions/index.html.erb
Too much space here and indentation sucks

<div class='container'>

<center>
    <img src="http://www.happyworker.com/files/imagecache/magazine_600/files/story/sleeping%20at%20work.jpg"><br><br><br></center>


  <% @questions.each_slice(3) do |question_row| %>
  <div class='row'>
    <% question_row.each do |question| %>
    <div class='col-md-4'>
        <div class="vote">

          <div class="well well-lg"><center>
            <h3><%= link_to question.title, question %></h3><br>
            // this is preferred
          <%= render "vote_form", votable: question, vote_boolean: true, new_vote: @vote, up_down: "^" %>
          <%= render partial: "vote_form", locals: { votable: question, vote_boolean: true, new_vote: @vote, up_down: "^" } %>
          <h3><%= question.score %></h3>
          <%= render partial: "vote_form", locals: { votable: question, vote_boolean: false, new_vote: @vote, up_down: "v" } %><br>
          <%= question.content %></center>
          </div>

        </div>

      </div>
      <% end %>
    </div>
    <% end %>
  </div>

app/views/questions/new.html.erb
<div class='container'><center>
<%= form_for @question do |f| -%>
  <%= f.text_field :title, placeholder: "Question" %><br /><br>
  <%= f.text_area :content, size: "40x7", placeholder: "Add some more details here." %><br /><br>
  <%= f.submit "create question", class: "btn btn-success" %>
<% end -%>
</center>
</div>

app/views/questions/show.html.erb
// formatting and indentation is terrible
<div class='container'><br><center>

<br><br><br><br> // try to avoid br and use styles
<div class="well well-sm"><br>
  <%= render partial: "vote_form", locals: { votable: @question, vote_boolean: true, new_vote: @vote, up_down: "upvote" } %>

  <h2 style="color:red">
    <%= @question.score %></h2><h2>

    <%= @question.title %>
  </h2>



<%= render partial: "vote_form", locals: { votable: @question, vote_boolean: false, new_vote: @vote, up_down: "downvote" } %><br>

<strong><%= @question.content %></strong><br><br>

</div>


<%= render partial: "add_answer_button", locals: { question: @question } %><br>

    <div class="well well-sm"><br>

<% @question.comments.each do |comment| %>
  <%= comment.content %><br>
<% end %>
<%= render partial: "comment_button", locals: { commentable: @question } %>
</div>

<% @answers.each_slice(1) do |answer_row|
answer_row.each do |answer| %>
    <div class="well well-sm"><br>

  <%= render partial: "best_answer_button", locals: { question: @question, answer_id: answer.id } %>

  <% if best_answer?(@question, answer.id) %>
    <h4>User Chosen Best Answer!</h4>
  <% end %>

  <%= render partial: "vote_form", locals: { votable: answer, vote_boolean: true, new_vote: @vote, up_down: "upvote" } %>
  <div><br>
    <h5 style="color:red"><%= answer.score %></h5>
  </div>

  <%= render partial: "vote_form", locals: { votable: answer, vote_boolean: false, new_vote: @vote, up_down: "downvote" } %>
  <br>
    <strong><%= answer.content %></strong>

  <% answer.comments.each do |comment| %>
    <%= comment.content %><br>
  <% end %><br>

  <%= render partial: "comment_button", locals: { commentable: answer } %>
</div>
<% end %>
<% end %>
</center>
</div>

app/views/users/new.html.erb
<center><%= form_for @user do |f|%>
  <%= f.text_field :username, placeholder: "username" %>
  <%= f.text_field :email, placeholder: "email" %><br>
  <%= f.password_field :password, placeholder: "password" %>
  <%= f.password_field :password_confirmation, placeholder: "confirm password" %><br><br>
  <%= f.submit 'create user', class: 'btn btn-success' %>
<% end %></center>

app/views/users/show.html.erb
<div class='container'><br><center>

  <div class="panel panel-success"><div class="panel-heading"><h3> my questions </h3></div></div><br>
  <% @user_questions.each_slice(1) do |question_row| %>
  <div class='row'>
    <% question_row.each do |question| %> 
    <div class='col-md-4'>
     <div class="well well-sm">
      <center>
        <h3><%= link_to question.title, question %></h3>
        <%= question.content %></center><br>
      </div>
    </div>
    <% end %>
    <% end %>
  </div><br><br>

  <div class="panel panel-danger"><div class="panel-heading"><h3> my answers </h3></div></div>
  <br><br>
  <% @user_answers.each_slice(1) do |answer_row| %>
  <div class='row'>
    <% answer_row.each do |this_answer| %>
    <div class='col-md-4'>
     <div class="well well-sm"><center>
      <strong>Answer:</strong> <%= this_answer.content  %><br>
      <strong>Question:</strong> <%= link_to this_answer.question.title, question_path(this_answer) %><br></center>
    </div>
  </div>
  <% end %>
  <% end %>


<br><br><br><br><br>
<div class="panel panel-warning"><div class="panel-heading"><h3> my comments </h3></div></div>
<br><br>    
<% @user_comments.each_slice(1) do |comment_row| %>
<div class='row'>
<% comment_row.each do |this_comment| %>
<div class='col-md-4'>
  <div class="well well-sm">
    <strong>Comment:</strong> <%= this_comment.content %><br>
    <% if this_comment.commentable_type == "Answer" %>
    <%= link_to this_comment.commentable.question.title, question_path(this_comment.commentable.question) %>
    <% else %>
    <%= link_to this_comment.commentable.title, question_path(this_comment.commentable) %>
    <%end%>
  </div>
</div>
<% end %>
<% end %>

</div>
</center>
</div>